import type {
  DashboardSettings,
  PortfolioCertification,
  PortfolioExperience,
  PortfolioProject,
} from "@/types/content";

export const defaultProjects: PortfolioProject[] = [
  {
    id: "featured-ransac-plane-segmentation",
    category: "featured",
    order: 1,
    image: "/images/page/projects/3d-plane-detection.png",
    title: "RANSAC Plane Segmentation with Temporal Tracking (CSC752)",
    description:
      "Developed multi-criteria plane classification system combining surface normals, height analysis, area estimation, and point density. Implemented temporal tracking with exponential smoothing (α=0.7) and label stability locking, processing 1,856 planes with 92.3% consistency at 30+ FPS on RGB-D data.",
    tags: [
      "ROS",
      "RANSAC",
      "Point Cloud Library",
      "Computer Vision",
      "Autonomous Navigation",
      "Python",
    ],
    demo: "https://github.com/pstepanovum/3d-plane-detection-for-robot-navigation",
  },
  {
    id: "featured-fmri-spectral-graph",
    category: "featured",
    order: 2,
    image: "/images/page/projects/brain-network.png",
    title: "fMRI Spectral Graph Signal Processing - Brain Connectivity Analysis",
    description:
      "Graph signal processing framework for analyzing fMRI brain networks and cognitive task classification. Achieved 67.1% accuracy using spectral decomposition with Random Forest, demonstrating interpretable frequency-domain analysis of neural connectivity patterns across motor, language, and working memory tasks.",
    tags: [
      "Python",
      "Graph Signal Processing",
      "Machine Learning",
      "Neuroimaging",
      "Scikit-learn",
      "NumPy/SciPy",
    ],
    demo: "https://github.com/pstepanovum/fMRI-Spectral-GSP",
  },
  {
    id: "featured-hough-plane-detection",
    category: "featured",
    order: 3,
    image: "/images/page/projects/hough-plane-detection.png",
    title: "Hough Transform Plane Detection for Robotic Navigation (ROS)",
    description:
      "Implemented enhanced D-KHT algorithm for real-time planar surface detection in 3D point clouds. Features O(1) statistical computations via Summed-Area Tables, PCA-based planarity validation, multi-projection analysis, and Isaac Sim integration. Achieves <50ms latency with Delaunay mesh reconstruction.",
    tags: [
      "ROS Noetic",
      "Computer Vision",
      "Python",
      "Point Cloud",
      "Isaac Sim",
      "LiDAR",
    ],
    demo: "https://github.com/pstepanovum/hough-plane-detection",
  },
  {
    id: "featured-buildcomply",
    category: "featured",
    order: 4,
    image: "/images/page/projects/buildcomply.png",
    title: "BuildComply - AI Construction Compliance SaaS (CTO Role)",
    description:
      "Architected and built enterprise SaaS platform as CTO, featuring intelligent PDF processing pipeline, NLP-powered code compliance validation, and complete Stripe payment integration. Achieved 90%+ approval rate with <30min processing time and 99.9% uptime across 50+ jurisdictions.",
    tags: [
      "TypeScript",
      "AI/ML",
      "NLP",
      "Stripe Payments",
      "REST API",
      "Cloud Infrastructure",
    ],
    demo: "https://github.com/pstepanovum/buildcomply",
  },
  {
    id: "featured-aml-monitoring",
    category: "featured",
    order: 5,
    image: "/images/page/projects/aml-detection.png",
    title: "AML Transaction Monitoring Database (ECE467 Database Systems)",
    description:
      "Comprehensive anti-money laundering detection system using HI-Small dataset. Features normalized 3NF schema, composite indexes for query optimization, 10 complex pattern detection algorithms (smurfing, layering, structuring), and specialized views for compliance officers and financial intelligence units.",
    tags: [
      "SQLite",
      "Database Design",
      "SQL",
      "Python",
      "Financial Analysis",
      "Pattern Detection",
    ],
    demo: "https://github.com/pstepanovum/ibm-transactions-for-anti-money-laundering-aml",
  },
  {
    id: "featured-voxel-engine",
    category: "featured",
    order: 6,
    image: "/images/page/projects/feature-p1.png",
    title: "3D Voxel Engine with Advanced Block Physics",
    description:
      "A multiplayer voxel game engine featuring DDA raycasting, procedural terrain generation with biomes, and real-time block synchronization across clients.",
    tags: ["Three.js", "WebGL", "Socket.IO", "WebWorkers"],
    github: "https://github.com/pstepanovum/minecraft-classic",
    demo: "https://minecraft-classic-theta.vercel.app/",
  },
  {
    id: "featured-health-haven",
    category: "featured",
    order: 7,
    image: "/images/page/projects/book.png",
    title: "Health Haven Software - Medical Operations Technology Upgrade",
    description:
      "Comprehensive medical operations technology upgrade for Regal Atlantic Cruiselines featuring EHR system modernization, real-time emergency response, enhanced cybersecurity, and mobile/offline access capabilities.",
    tags: [
      "React.js",
      "Node.js",
      "PostgreSQL",
      "AWS",
      "CrowdStrike",
      "Apache Kafka",
    ],
    demo: "/",
  },
  {
    id: "featured-covid-ct-analysis",
    category: "featured",
    order: 8,
    image: "/images/page/projects/covid.png",
    title: "COVID-19 CT Image Analysis",
    description:
      "Deep learning system for COVID-19 detection from CT scans using ResNet and advanced visualization techniques. Achieves high accuracy through transfer learning and custom model implementations.",
    tags: ["PyTorch", "ResNet", "Transfer Learning", "GradCAM", "Medical AI"],
    github: "https://github.com/pstepanovum",
    demo: "/",
  },
  {
    id: "web-goldenrod",
    category: "webApps",
    order: 1,
    image: "/images/page/projects/1.png",
    title: "Goldenrod: Cloud-Native Crypto Portfolio Platform",
    description:
      "A comprehensive cryptocurrency portfolio tracking application demonstrating full-stack DevOps implementation. Features include automated CI/CD pipelines with Jenkins, containerized microservices using Docker and Kubernetes, infrastructure as code with Terraform on AWS, and robust monitoring using Prometheus and Grafana. The platform handles real-time crypto data processing, automated testing, and zero-downtime deployments, showcasing modern DevOps practices and cloud-native architecture.",
    tags: [
      "Next.js",
      "AWS",
      "Docker",
      "Kubernetes",
      "Terraform",
      "Jenkins",
      "Prometheus",
      "Grafana",
      "CI/CD",
    ],
    github: "https://github.com/pstepanovum",
    demo: "https://github.com/pstepanovum",
  },
  {
    id: "web-resonate-ai",
    category: "webApps",
    order: 2,
    image: "/images/page/projects/resonateai.png",
    title: "ResonateAI DiffRhythm - Neural Music Generation Interface",
    description:
      "Full-stack AI music generation platform leveraging DiffRhythm diffusion model. Features React Query data fetching, Howler.js audio engine, Flask API with Librosa processing, and MuQ/MuQ-MuLan music representation. Enables lyrics-to-song generation with real-time progress and responsive audio controls.",
    tags: [
      "Next.js",
      "TypeScript",
      "Flask",
      "Diffusion Models",
      "Librosa",
      "React Query",
    ],
    demo: "https://github.com/pstepanovum/resonateAI",
  },
  {
    id: "web-therapy-ai",
    category: "webApps",
    order: 3,
    image: "/images/page/projects/therapy-ai.png",
    title: "TherapyAI: Mental Health Support Platform",
    description:
      "A comprehensive platform that helps therapists and patients stay present in every session—capturing conversations, revealing patterns and summarizing therapy sessions. Features include AI-generated session summaries, mindful journaling prompts, separate dashboards for patients and therapists, secure video sessions, and message management. Built with a focus on privacy and seamless multi-service integration.",
    tags: [
      "Next.js",
      "Firebase",
      "LiveKit",
      "AWS S3",
      "OpenAI API",
      "Whisper API",
      "GPT-4",
    ],
    github: "https://github.com/pstepanovum/therapyai",
    demo: "https://devpost.com/software/therapyai-4jl26m",
  },
  {
    id: "web-lokin",
    category: "webApps",
    order: 4,
    image: "/images/page/projects/lokin.png",
    title: "Lokin - AI-Powered Student Startup Networking Platform",
    description:
      "First on-campus AI networking platform connecting students with startup opportunities. Built full-stack prototype featuring team matching algorithms, project management tools, and profile systems. Enables 500+ students across 5 universities to find co-founders, join startups, and build portfolio-ready experience.",
    tags: [
      "React",
      "Next.js",
      "TypeScript",
      "AI Matching",
      "Full-Stack",
      "Product Design",
    ],
    demo: "https://www.lokin.io/",
  },
  {
    id: "ai-fmri-spectral-graph",
    category: "ai",
    order: 1,
    image: "/images/page/projects/brain-network.png",
    title: "fMRI Spectral Graph Signal Processing - Brain Connectivity Analysis",
    description:
      "Graph signal processing framework for analyzing fMRI brain networks and cognitive task classification. Achieved 67.1% accuracy using spectral decomposition with Random Forest, demonstrating interpretable frequency-domain analysis of neural connectivity patterns across motor, language, and working memory tasks.",
    tags: [
      "Python",
      "Graph Signal Processing",
      "Machine Learning",
      "Neuroimaging",
      "Scikit-learn",
      "NumPy/SciPy",
    ],
    demo: "https://github.com/pstepanovum/fMRI-Spectral-GSP",
  },
  {
    id: "ai-covid-ct-analysis",
    category: "ai",
    order: 2,
    image: "/images/page/projects/covid.png",
    title: "COVID-19 CT Image Analysis",
    description:
      "Deep learning system for COVID-19 detection from CT scans using ResNet and advanced visualization techniques. Achieves high accuracy through transfer learning and custom model implementations.",
    tags: ["PyTorch", "ResNet", "Transfer Learning", "GradCAM", "Medical AI"],
    github: "https://github.com/pstepanovum",
    demo: "/",
  },
  {
    id: "ai-agario-engine",
    category: "ai",
    order: 3,
    image: "/images/page/projects/2.png",
    title: "Agario AI Game Engine",
    description:
      "Developed intelligent AI agents for a multiplayer blob game inspired by Agar.io. Implemented sophisticated behaviors including strategic blob movement, size-based pursuit and avoidance decisions, and automated splitting mechanics. Features real-time decision making and adaptive gameplay strategies.",
    tags: [
      "Neural Networks",
      "Reinforcement Learning",
      "Game AI",
      "JavaScript",
      "Node.js",
    ],
    github: "https://github.com/pstepanovum/agar.io-clone",
    demo: "https://agar-io-clone-8std.vercel.app",
  },
  {
    id: "ai-minecraft-hide-seek",
    category: "ai",
    order: 4,
    image: "/images/page/projects/3.png",
    title: "Minecraft AI Hide & Seek (Upcoming)",
    description:
      "Designing an advanced AI system for NPCs in a Minecraft-style hide-and-seek game. Will feature intelligent pathfinding, strategic block manipulation, and cooperative team behaviors. NPCs will execute complex strategies like tree concealment, underground burrowing, and elevation tactics while maintaining efficient block inventory management.",
    tags: [
      "Reinforcement Learning",
      "Pathfinding Algorithms",
      "Game Theory",
      "JavaScript",
      "THREE.js",
    ],
    github:
      "https://lucky-quokka-0a7.notion.site/Full-Stack-Development-001-1133d74755a8807aadd0fe1890d31aad?pvs=4",
    demo: "https://lucky-quokka-0a7.notion.site/Full-Stack-Development-001-1133d74755a8807aadd0fe1890d31aad?pvs=4",
  },
];

export const defaultCertifications: PortfolioCertification[] = [
  {
    id: "foundations-of-cybersecurity",
    order: 1,
    title: "Foundations of Cybersecurity",
    issuer: "Google",
    date: "Issued Jan 2025",
    credentialId: "6HK4U0WAXGNS",
    skills: [
      "Cybersecurity fundamentals",
      "Security protocols",
      "Risk management",
      "Network security",
    ],
    logo: "/images/page/skills/certificates/google.png",
  },
  {
    id: "google-data-analytics",
    order: 2,
    title: "Google Data Analytics Professional Certificate",
    issuer: "Google",
    date: "Issued Nov 2024",
    credentialId: "O0O4FBOY3YLD",
    skills: [
      "Data analysis",
      "SQL",
      "R programming",
      "Data visualization",
      "Statistical analysis",
    ],
    logo: "/images/page/skills/certificates/google.png",
  },
  {
    id: "campaign-manager-360",
    order: 3,
    title: "Campaign Manager 360",
    issuer: "Google",
    date: "Issued Sep 2024 · Expires Sep 2025",
    credentialId: "CM360-2024-09",
    skills: [
      "Agency Planners",
      "Trafficker",
      "Campaign management",
      "Digital advertising",
    ],
    logo: "/images/page/skills/certificates/google.png",
  },
  {
    id: "ef-set-english-certificate",
    order: 4,
    title: "EF SET English Certificate",
    issuer: "EF SET",
    date: "Issued Sep 2024 · Expires Sep 2025",
    credentialId: "EFSET-2024-09",
    skills: [
      "English proficiency",
      "Business communication",
      "Written comprehension",
      "Verbal communication",
    ],
    logo: "/images/page/skills/certificates/ef.png",
  },
  {
    id: "google-analytics",
    order: 5,
    title: "Google Analytics",
    issuer: "Google",
    date: "Issued Sep 2024 · Expires Sep 2025",
    credentialId: "e2a27c17-f734-4a4d-b1e2-b004b9108f11",
    skills: [
      "Google Analytics 4 property setup",
      "Data collection and analysis",
      "Reporting tools utilization",
      "Key measurement features",
      "Website and app analytics",
    ],
    logo: "/images/page/skills/certificates/google.png",
  },
];

export const defaultExperiences: PortfolioExperience[] = [
  {
    id: "spectral-graph-signal-processing",
    order: 1,
    date: "Nov 2024 - Dec 2024",
    title: "Research Project: Spectral Graph Signal Processing",
    company: "University of Miami - ECE735",
    location: "Coral Gables, FL",
    type: "Academic Research",
    description:
      "Applied graph signal processing techniques to fMRI brain networks for cognitive task classification using Human Connectome Project data.",
    achievements: [
      "Achieved 67.1% classification accuracy distinguishing motor, language, and working memory tasks using spectral features with Random Forest classifier",
      "Implemented complete neuroimaging pipeline from data preprocessing through spectral decomposition to machine learning classification",
      "Reduced dimensionality from 79,800 features to 20 interpretable spectral frequency bands while maintaining competitive performance",
      "Demonstrated that spectral GSP features outperform raw connectivity in small-sample regimes (47.9% vs 32.9% with N=16 subjects)",
      "Published open-source implementation with comprehensive documentation following reproducible research practices",
    ],
    tech: [
      "Python",
      "NumPy/SciPy",
      "Nilearn",
      "PyGSP",
      "Scikit-learn",
      "Graph Signal Processing",
      "Machine Learning",
      "fMRI Analysis",
      "Statistical Analysis",
    ],
  },
  {
    id: "it-services-specialist",
    order: 2,
    date: "Fall 2023 - Fall 2024",
    title: "IT Services Specialist",
    company: "University of Miami Herbert Business School",
    location: "Miami, FL",
    description:
      "Led technical infrastructure improvements and automation initiatives in an educational environment. Focused on process optimization and team leadership.",
    achievements: [
      "Engineered automated solutions using Python and REST APIs, achieving 40% reduction in manual processes",
      "Implemented agile methodologies for system upgrade projects, managing sprints and deliverables",
      "Led and mentored cross-functional team of 3 specialists, establishing automation and testing best practices",
      "Maintained 95% user satisfaction rate through systematic problem-solving approaches",
    ],
    tech: ["Python", "REST APIs", "Agile", "Automation Testing"],
  },
  {
    id: "software-developer-current-newspaper",
    order: 3,
    date: "Oct 2022 - Jun 2023",
    title: "Software Developer",
    company: "The Current Newspaper",
    location: "Auburn, WA",
    description:
      "Developed and maintained web applications with focus on content management and API integrations.",
    achievements: [
      "Architected and implemented API integrations for content syndication, boosting workflow efficiency by 40%",
      "Collaborated in agile environment utilizing weekly sprints and peer code reviews",
      "Applied SDLC best practices in full-stack website redesign and feature implementation",
    ],
    tech: ["API Development", "SDLC", "Agile", "Full-Stack Development"],
  },
  {
    id: "computer-technician",
    order: 4,
    date: "Jun 2022 - Dec 2022",
    title: "Computer Technician",
    company: "Green River PC Repair Shop",
    location: "Auburn, WA",
    description:
      "Provided technical solutions and implemented content management systems for small businesses.",
    achievements: [
      "Developed and maintained content management solutions for small business websites",
      "Performed comprehensive hardware diagnostics and system repairs for 100+ clients",
      "Created and maintained technical documentation repository for procedures and solutions",
    ],
    tech: [
      "CMS",
      "Hardware Diagnostics",
      "Technical Documentation",
      "System Repair",
    ],
  },
  {
    id: "technical-sales-specialist",
    order: 5,
    date: "Jun 2022 - Aug 2022",
    title: "Technical Sales Specialist",
    company: "LA Fitness",
    location: "Auburn, WA",
    description:
      "Implemented technical solutions for sales and customer relationship management.",
    achievements: [
      "Developed automated tracking system using Excel and VBA for lead management",
      "Built and maintained CRM database system for 500+ members with data analytics",
      "Created automated email campaign system improving communication efficiency by 30%",
      "Implemented digital calendar integration for streamlined appointment booking",
    ],
    tech: [
      "Excel Analytics",
      "VBA",
      "CRM Systems",
      "Automation",
      "Data Analysis",
    ],
  },
  {
    id: "web-developer-ui-designer",
    order: 6,
    date: "Feb 2021 - Jan 2022",
    title: "Web Developer & UI Designer",
    company: "Sports Contour",
    location: "Irkutsk, Russia",
    type: "Remote",
    description:
      "Full-stack web development and UI/UX design for sports equipment company.",
    achievements: [
      "Developed responsive website layouts and interfaces using modern web technologies",
      "Implemented UI/UX improvements resulting in enhanced user engagement",
      "Created design system and component library for consistent brand presentation",
      "Built interactive product catalogs with advanced filtering and search capabilities",
    ],
    tech: [
      "HTML/CSS",
      "JavaScript",
      "UI/UX Design",
      "Photoshop",
      "Zbrush",
      "Responsive Design",
    ],
  },
];

export const defaultDashboardSettings: DashboardSettings = {
  geminiModel: "gemini-2.5-flash",
  geminiApiKey: "",
  projectDraftPrompt:
    "Write polished but direct portfolio project entries. Keep descriptions specific, quantify outcomes when possible, and return concise tags that match the technologies actually used.",
  llmPublicKey: "",
  llmSecretKey: "",
  resumeUrl: "",
  resumeStoragePath: "",
  resumePassword: "",
  resumeIsPublic: false,
};
