import "server-only";

import { gunzipSync, gzipSync } from "node:zlib";
import { FieldValue, Timestamp } from "firebase-admin/firestore";
import { adminDb } from "@/lib/firebase/admin-core";
import { buildCacheKey, type Chapter, type TranscriptCue } from "@/lib/youtube/transcript-text";

/**
 * Transcript cache and fetch counters.
 *
 * A caption track never changes once it exists, so every successful fetch is
 * worth keeping: it turns a repeat question about the same podcast into one
 * Firestore read, and it is the only thing that makes the tool usable at all
 * on days when YouTube is throttling this server's address.
 */

const COLLECTION = "youtubeTranscripts";
const STATS_COLLECTION = "youtubeTranscriptStats";

/** Firestore caps a document at 1 MiB; leave room for the metadata. */
const MAX_COMPRESSED_BYTES = 850_000;

export type CachedTranscript = {
  videoId: string;
  title: string;
  channel: string;
  durationSeconds: number;
  publishedAt?: string;
  languageCode: string;
  languageName: string;
  autoGenerated: boolean;
  translated: boolean;
  chapters: Chapter[];
  cues: TranscriptCue[];
  fetchedAt: string;
};

type AliasDocument = { alias: string };

function isAlias(data: Record<string, unknown> | undefined): data is AliasDocument {
  return typeof data?.alias === "string";
}

function toBuffer(value: unknown) {
  if (Buffer.isBuffer(value)) {
    return value;
  }

  // The Node SDK hands bytes back as a Uint8Array-like wrapper.
  if (value && typeof value === "object" && "toUint8Array" in value) {
    return Buffer.from((value as { toUint8Array(): Uint8Array }).toUint8Array());
  }

  if (value instanceof Uint8Array) {
    return Buffer.from(value);
  }

  return null;
}

function readDocument(
  key: string,
  data: Record<string, unknown>,
): CachedTranscript | null {
  const buffer = toBuffer(data.cues);

  if (!buffer) {
    return null;
  }

  let cues: TranscriptCue[];

  try {
    cues = JSON.parse(gunzipSync(buffer).toString("utf8")) as TranscriptCue[];
  } catch {
    return null;
  }

  if (!Array.isArray(cues) || cues.length === 0) {
    return null;
  }

  const fetchedAt = data.fetchedAt instanceof Timestamp ? data.fetchedAt.toDate() : new Date(0);

  return {
    videoId: String(data.videoId ?? key.split("__")[0]),
    title: String(data.title ?? ""),
    channel: String(data.channel ?? ""),
    durationSeconds: Number(data.durationSeconds ?? 0),
    publishedAt: typeof data.publishedAt === "string" ? data.publishedAt : undefined,
    languageCode: String(data.languageCode ?? ""),
    languageName: String(data.languageName ?? ""),
    autoGenerated: data.autoGenerated === true,
    translated: data.translated === true,
    chapters: Array.isArray(data.chapters) ? (data.chapters as Chapter[]) : [],
    cues,
    fetchedAt: fetchedAt.toISOString(),
  };
}

/**
 * Looks a transcript up by video and requested language. A request that named
 * no language is stored as a pointer at the resolved one, so asking for "the
 * default" and then for "en" does not fetch the same podcast twice.
 */
export async function readCachedTranscript(videoId: string, language?: string) {
  const key = buildCacheKey(videoId, language);
  const snapshot = await adminDb.collection(COLLECTION).doc(key).get();

  if (!snapshot.exists) {
    return null;
  }

  const data = snapshot.data() as Record<string, unknown>;

  if (isAlias(data)) {
    const target = await adminDb.collection(COLLECTION).doc(data.alias).get();

    return target.exists
      ? readDocument(data.alias, target.data() as Record<string, unknown>)
      : null;
  }

  return readDocument(key, data);
}

/**
 * Stores under the resolved language, and adds a pointer from the requested
 * key when the caller asked for something else (or for nothing).
 */
export async function writeCachedTranscript(
  transcript: Omit<CachedTranscript, "fetchedAt">,
  requestedLanguage?: string,
) {
  const compressed = gzipSync(Buffer.from(JSON.stringify(transcript.cues), "utf8"));

  if (compressed.byteLength > MAX_COMPRESSED_BYTES) {
    // A transcript this large would not fit in one document. Refetching it is
    // slow but correct; a half-stored one would not be.
    return false;
  }

  const resolvedKey = buildCacheKey(transcript.videoId, transcript.languageCode);
  const requestedKey = buildCacheKey(transcript.videoId, requestedLanguage);
  const batch = adminDb.batch();

  batch.set(adminDb.collection(COLLECTION).doc(resolvedKey), {
    videoId: transcript.videoId,
    title: transcript.title,
    channel: transcript.channel,
    durationSeconds: transcript.durationSeconds,
    publishedAt: transcript.publishedAt ?? null,
    languageCode: transcript.languageCode,
    languageName: transcript.languageName,
    autoGenerated: transcript.autoGenerated,
    translated: transcript.translated,
    chapters: transcript.chapters,
    cues: compressed,
    cueCount: transcript.cues.length,
    fetchedAt: FieldValue.serverTimestamp(),
  });

  if (requestedKey !== resolvedKey) {
    batch.set(adminDb.collection(COLLECTION).doc(requestedKey), {
      alias: resolvedKey,
      fetchedAt: FieldValue.serverTimestamp(),
    });
  }

  await batch.commit();

  return true;
}

export type FetchOutcome =
  | "hit"
  | "fetched"
  | "blocked"
  | "no_captions"
  | "unavailable"
  | "language_unavailable"
  | "error";

/**
 * One counter document per UTC day. Enough to answer "how often is YouTube
 * refusing us this week?" without storing a row per attempt, and it is the
 * only record of a refusal that never reached the tool result.
 */
export async function recordFetchOutcome(outcome: FetchOutcome, detail?: string) {
  try {
    const day = new Date().toISOString().slice(0, 10);

    await adminDb
      .collection(STATS_COLLECTION)
      .doc(day)
      .set(
        {
          day,
          [outcome]: FieldValue.increment(1),
          total: FieldValue.increment(1),
          updatedAt: FieldValue.serverTimestamp(),
          ...(detail && outcome !== "hit" && outcome !== "fetched"
            ? { lastError: detail.slice(0, 500), lastErrorAt: FieldValue.serverTimestamp() }
            : {}),
        },
        { merge: true },
      );
  } catch {
    // Counters must never break a transcript.
  }
}

export type TranscriptStatsDay = {
  day: string;
  total: number;
  hit: number;
  fetched: number;
  blocked: number;
  failed: number;
  lastError?: string;
};

/** Recent days of counters, newest first, for the dashboard. */
export async function listTranscriptStats(days = 14): Promise<TranscriptStatsDay[]> {
  const snapshot = await adminDb
    .collection(STATS_COLLECTION)
    .orderBy("day", "desc")
    .limit(Math.min(Math.max(days, 1), 90))
    .get();

  return snapshot.docs.map((doc) => {
    const data = doc.data() as Record<string, unknown>;
    const count = (key: string) => (typeof data[key] === "number" ? (data[key] as number) : 0);

    return {
      day: typeof data.day === "string" ? data.day : doc.id,
      total: count("total"),
      hit: count("hit"),
      fetched: count("fetched"),
      blocked: count("blocked"),
      failed: count("no_captions") + count("unavailable") + count("language_unavailable") + count("error"),
      lastError: typeof data.lastError === "string" ? data.lastError : undefined,
    };
  });
}
