import "server-only";

import {
  readCachedTranscript,
  recordFetchOutcome,
  writeCachedTranscript,
  type CachedTranscript,
  type FetchOutcome,
} from "@/lib/youtube/cache";
import { YouTubeTranscriptError } from "@/lib/youtube/errors";
import {
  fetchCues,
  fetchPlayerData,
  type CaptionTrack,
  type PlayerData,
} from "@/lib/youtube/innertube";
import {
  parseChaptersFromDescription,
  type TranscriptCue,
} from "@/lib/youtube/transcript-text";

/** Maps a thrown failure onto the counter it belongs in. */
function outcomeFor(error: unknown): FetchOutcome {
  if (!(error instanceof YouTubeTranscriptError)) {
    return "error";
  }

  switch (error.code) {
    case "blocked":
      return "blocked";
    case "no_captions":
      return "no_captions";
    case "unavailable":
      return "unavailable";
    case "language_unavailable":
      return "language_unavailable";
    default:
      return "error";
  }
}

export type TranscriptTrackChoice = {
  track: CaptionTrack;
  translateTo?: string;
  languageCode: string;
  languageName: string;
  autoGenerated: boolean;
  translated: boolean;
  /** One sentence naming the track that was used, for the tool's answer. */
  note: string;
};

/** BCP 47 shapes YouTube actually uses: "en", "pt-BR", "es-419". */
const PLAUSIBLE_LANGUAGE = /^[a-z]{2,3}(-[A-Za-z0-9]{2,8})?$/;

function sameLanguage(a: string, b: string) {
  const left = a.toLowerCase();
  const right = b.toLowerCase();

  return left === right || left.split("-")[0] === right.split("-")[0];
}

function describe(track: CaptionTrack) {
  return `${track.languageName}${track.autoGenerated ? " (auto-generated)" : ""}`;
}

/**
 * Language picking: the language asked for, else the track the player itself
 * treats as the video's own, else English, else whatever exists. Only if no
 * real track matches does it fall back to an auto-translation, and the answer
 * always says which of those happened.
 */
export function chooseTrack(player: PlayerData, requested?: string): TranscriptTrackChoice {
  const { tracks, translationLanguages, defaultTrackIndex } = player;
  const manualFirst = (candidates: CaptionTrack[]) =>
    candidates.find((track) => !track.autoGenerated) ?? candidates[0];

  const build = (
    track: CaptionTrack,
    note: string,
    translateTo?: string,
    translationName?: string,
  ): TranscriptTrackChoice => ({
    track,
    translateTo,
    languageCode: translateTo ?? track.languageCode,
    languageName: translateTo ? (translationName ?? translateTo) : track.languageName,
    autoGenerated: track.autoGenerated,
    translated: Boolean(translateTo),
    note,
  });

  if (requested) {
    const matches = tracks.filter((track) => sameLanguage(track.languageCode, requested));

    if (matches.length > 0) {
      const track = manualFirst(matches);

      return build(track, `Used the ${describe(track)} caption track.`);
    }

    // Some player responses carry no translation list at all. YouTube will
    // still translate a translatable track, so a plausible-looking code is
    // worth trying rather than refusing outright.
    const translation =
      translationLanguages.find((language) => sameLanguage(language.languageCode, requested)) ??
      (translationLanguages.length === 0 && PLAUSIBLE_LANGUAGE.test(requested)
        ? { languageCode: requested, languageName: requested }
        : undefined);
    const translatable = tracks.filter((track) => track.translatable);

    if (translation && translatable.length > 0) {
      const source = manualFirst(translatable);

      return build(
        source,
        `No ${translation.languageName} captions exist for this video, so the ${describe(
          source,
        )} track was auto-translated into ${translation.languageName}. Machine translation of a machine transcript: read it as a rough guide.`,
        translation.languageCode,
        translation.languageName,
      );
    }

    throw new YouTubeTranscriptError(
      `This video has no captions in "${requested}". Available: ${
        tracks.map((track) => `${track.languageCode}${track.autoGenerated ? " (auto)" : ""}`).join(", ") ||
        "none"
      }.`,
      "language_unavailable",
      false,
    );
  }

  const preferred =
    (defaultTrackIndex !== null ? tracks[defaultTrackIndex] : undefined) ??
    tracks.find((track) => !track.autoGenerated) ??
    tracks.find((track) => sameLanguage(track.languageCode, "en")) ??
    tracks[0];

  return build(preferred, `Used the ${describe(preferred)} caption track, the video's own.`);
}

export type TranscriptResult = CachedTranscript & {
  cache: { hit: boolean; stored: boolean };
  /** Which InnerTube client answered; empty on a cache hit. */
  client?: string;
  note: string;
};

/**
 * Cache first, then YouTube. Every outcome, including a refusal that never
 * reaches the caller as data, is counted so the failure rate is visible.
 */
export async function getTranscript(
  videoId: string,
  options: { language?: string; refresh?: boolean } = {},
): Promise<TranscriptResult> {
  if (!options.refresh) {
    const cached = await readCachedTranscript(videoId, options.language).catch(() => null);

    if (cached) {
      await recordFetchOutcome("hit");

      return {
        ...cached,
        cache: { hit: true, stored: true },
        note: `Used the ${cached.languageName}${cached.autoGenerated ? " (auto-generated)" : ""}${
          cached.translated ? ", auto-translated" : ""
        } caption track, from the cached copy fetched ${cached.fetchedAt.slice(0, 10)}.`,
      };
    }
  }

  let player: PlayerData;

  try {
    player = await fetchPlayerData(videoId);
  } catch (error) {
    await recordFetchOutcome(
      outcomeFor(error),
      error instanceof Error ? error.message : String(error),
    );

    throw error;
  }

  let choice: TranscriptTrackChoice;
  let cues: TranscriptCue[];

  try {
    choice = chooseTrack(player, options.language);
    cues = await fetchCues(choice.track, choice.translateTo);
  } catch (rawError) {
    // Which client supplied the track list matters when the cues then fail:
    // it is the difference between a transient refusal and a stale URL.
    const error =
      rawError instanceof YouTubeTranscriptError && rawError.code === "blocked"
        ? new YouTubeTranscriptError(
            `${rawError.message} (Caption list came from the ${player.client} player.)`,
            "blocked",
            true,
          )
        : rawError;

    await recordFetchOutcome(
      outcomeFor(error),
      error instanceof Error ? error.message : String(error),
    );

    throw error;
  }

  const transcript = {
    videoId: player.video.id,
    title: player.video.title,
    channel: player.video.channel,
    durationSeconds: player.video.durationSeconds,
    publishedAt: player.video.publishedAt,
    languageCode: choice.languageCode,
    languageName: choice.languageName,
    autoGenerated: choice.autoGenerated,
    translated: choice.translated,
    chapters: parseChaptersFromDescription(player.video.description, player.video.durationSeconds),
    cues,
  };

  const stored = await writeCachedTranscript(transcript, options.language).catch(() => false);

  await recordFetchOutcome("fetched");

  return {
    ...transcript,
    fetchedAt: new Date().toISOString(),
    cache: { hit: false, stored },
    client: player.client,
    note: choice.note,
  };
}
