import "server-only";

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { errorResult, jsonResult } from "@/lib/mcp/format";
import { TRANSCRIPT_FOLDER, saveTranscriptToDrive } from "@/lib/youtube/drive";
import { YouTubeTranscriptError } from "@/lib/youtube/errors";
import { getTranscript } from "@/lib/youtube/transcript";
import {
  countWords,
  formatTimestamp,
  renderTranscript,
  transcriptFileName,
  type TranscriptFormat,
} from "@/lib/youtube/transcript-text";
import { parseVideoId, watchUrl } from "@/lib/youtube/video-url";

/**
 * One personal utility: paste a YouTube link, get the words.
 *
 * Deliberately single-video. There is no bulk mode and no queue, because the
 * point is reading back something already watched, not harvesting YouTube.
 */

const DEFAULT_INLINE_CHARS = 2000;

const ANNOTATIONS = {
  readOnlyHint: false,
  destructiveHint: false,
  // Re-running for the same video reuses the file already in the folder.
  idempotentHint: true,
  openWorldHint: true,
} as const;

const DESCRIPTION = [
  "Fetch a YouTube video's captions as text. Accepts any link shape (youtu.be/ID, watch?v=ID, /shorts/, /live/, with tracking parameters) or a bare video id.",
  `Long videos are not dumped into the chat: by default only the first ${DEFAULT_INLINE_CHARS} characters come back inline and the full .txt is saved to the connected Google account's Drive, in a "${TRANSCRIPT_FOLDER}" folder, with the link returned.`,
  "Set save_to_drive false for a short video you just want to read here, or raise inline_chars.",
  "format: clean (default, reflowed paragraphs with caption noise and auto-caption stutter removed), stamps (same, with a timestamp on each paragraph for jumping back), raw (the cue list with start times).",
  "Chapters become headings when the video has them. Transcripts are cached, so asking twice costs nothing.",
].join(" ");

function truncateAtBoundary(text: string, limit: number) {
  if (limit <= 0) {
    return { head: "", truncated: text.length > 0 };
  }

  if (text.length <= limit) {
    return { head: text, truncated: false };
  }

  const slice = text.slice(0, limit);
  const breakAt = Math.max(slice.lastIndexOf("\n\n"), slice.lastIndexOf(" "));

  return {
    head: (breakAt > limit * 0.5 ? slice.slice(0, breakAt) : slice).trimEnd(),
    truncated: true,
  };
}

function fileHeader(input: {
  title: string;
  channel: string;
  url: string;
  duration: string;
  language: string;
  autoGenerated: boolean;
  translated: boolean;
  words: number;
  fetchedAt: string;
}) {
  return [
    input.title,
    [input.channel, input.duration].filter(Boolean).join(" · "),
    input.url,
    `Captions: ${input.language}${input.autoGenerated ? " (auto-generated)" : ""}${
      input.translated ? ", auto-translated" : ""
    }`,
    `${input.words.toLocaleString("en-US")} words · fetched ${input.fetchedAt.slice(0, 10)}`,
    "",
    "-".repeat(60),
    "",
  ].join("\n");
}

/**
 * Registered behind google:read. The Drive save additionally needs
 * google:write, which `driveWritable` carries in; without it the tool still
 * works and says plainly why nothing was filed.
 */
export function registerYouTubeTools(
  server: McpServer,
  options: { driveWritable?: boolean } = {},
) {
  const driveWritable = options.driveWritable !== false;

  server.registerTool(
    "get_youtube_transcript",
    {
      title: "Get a YouTube transcript",
      description: DESCRIPTION,
      inputSchema: {
        url: z
          .string()
          .trim()
          .min(1)
          .describe("The video link, in any YouTube URL shape, or a bare 11-character video id."),
        lang: z
          .string()
          .trim()
          .min(2)
          .max(10)
          .optional()
          .describe(
            'Language code for the caption track, e.g. "en" or "pt-BR". Defaults to the video\'s own track; falls back to English, then to an auto-translation.',
          ),
        format: z
          .enum(["clean", "stamps", "raw"])
          .optional()
          .describe("clean (default), stamps, or raw."),
        save_to_drive: z
          .boolean()
          .optional()
          .describe(
            "Force the .txt into Drive (true) or keep it out (false). Left unset, it is saved whenever the transcript is longer than inline_chars.",
          ),
        inline_chars: z
          .number()
          .int()
          .min(0)
          .max(200_000)
          .optional()
          .describe(`How much of the transcript to return in the response. Default ${DEFAULT_INLINE_CHARS}.`),
        account: z
          .string()
          .trim()
          .min(1)
          .optional()
          .describe(
            "Which connected Google account's Drive to save into: alias, email, or id. Optional when exactly one account is connected.",
          ),
        refresh: z
          .boolean()
          .optional()
          .describe("Ignore the cached copy and fetch the captions again."),
      },
      annotations: ANNOTATIONS,
    },
    async ({ url, lang, format, save_to_drive: saveToDrive, inline_chars: inlineChars, account, refresh }) => {
      const videoId = parseVideoId(url);

      if (!videoId) {
        return errorResult(
          `"${url}" is not a YouTube video link. Give a watch, youtu.be, shorts, or live URL, or the 11-character video id.`,
        );
      }

      let transcript;

      try {
        transcript = await getTranscript(videoId, { language: lang, refresh });
      } catch (error) {
        if (error instanceof YouTubeTranscriptError) {
          // The code is in the text on purpose: "blocked" must never be read
          // as "this video has no captions", and only one of the two is worth
          // retrying.
          return errorResult(`[${error.code}] ${error.message}`);
        }

        return errorResult(
          `The transcript could not be fetched: ${
            error instanceof Error ? error.message : "unknown error"
          }`,
        );
      }

      const chosenFormat = (format ?? "clean") as TranscriptFormat;
      const text = renderTranscript({
        format: chosenFormat,
        cues: transcript.cues,
        chapters: transcript.chapters,
        durationSeconds: transcript.durationSeconds,
      });

      if (!text.trim()) {
        return errorResult(
          "[blocked] The caption track came back empty. That is throttling rather than a video without captions; try again in a few minutes.",
        );
      }

      const words = countWords(text);
      const limit = inlineChars ?? DEFAULT_INLINE_CHARS;
      const limitWasAskedFor = inlineChars !== undefined;
      const wantsDrive = saveToDrive ?? text.length > limit;
      const videoUrl = watchUrl(videoId);
      const duration = transcript.durationSeconds ? formatTimestamp(transcript.durationSeconds) : "";

      let drive:
        | Awaited<ReturnType<typeof saveTranscriptToDrive>>
        | { saved: false; reason: string } = {
        saved: false,
        reason: "Not requested; the transcript is inline.",
      };

      if (wantsDrive && !driveWritable) {
        drive = {
          saved: false,
          reason:
            "This connection was not granted google:write, so nothing can be written to Drive. Re-approve it with google:write at /dashboard/connections, or read the transcript inline.",
        };
      } else if (wantsDrive) {
        drive = await saveTranscriptToDrive({
          account,
          name: transcriptFileName(transcript.title, videoId),
          content:
            fileHeader({
              title: transcript.title,
              channel: transcript.channel,
              url: videoUrl,
              duration,
              language: transcript.languageName,
              autoGenerated: transcript.autoGenerated,
              translated: transcript.translated,
              words,
              fetchedAt: transcript.fetchedAt,
            }) + text,
        });
      }

      // When Drive took the file the inline head stays short. When it did not,
      // the whole transcript comes back rather than being lost — unless a
      // deliberate inline_chars said how much was wanted.
      const inlineLimit =
        drive.saved || limitWasAskedFor ? limit : Math.max(limit, text.length);
      const { head, truncated } = truncateAtBoundary(text, inlineLimit);

      return jsonResult({
        video: {
          id: videoId,
          title: transcript.title,
          channel: transcript.channel,
          url: videoUrl,
          duration,
          durationSeconds: transcript.durationSeconds,
          publishedAt: transcript.publishedAt,
        },
        captions: {
          language: transcript.languageName,
          languageCode: transcript.languageCode,
          autoGenerated: transcript.autoGenerated,
          translated: transcript.translated,
          track: transcript.note,
        },
        transcript: {
          format: chosenFormat,
          words,
          characters: text.length,
          cues: transcript.cues.length,
          chapters: transcript.chapters.length,
          truncated,
          text: head,
          ...(truncated
            ? {
                omitted: `${(text.length - head.length).toLocaleString("en-US")} more characters were left out${
                  drive.saved ? " here; the Drive file has all of them" : ""
                }. Raise inline_chars to see more.`,
              }
            : {}),
        },
        drive,
        cache: {
          hit: transcript.cache.hit,
          stored: transcript.cache.stored,
          fetchedAt: transcript.fetchedAt,
        },
      });
    },
  );
}
